$(document).ready(function(){
	$("#kirim").click(function(){
		$("#nama").text(
			$("#fnama").val()
		);
		$("#alamat").text(
			$("#falamat").val()
		);
		$("#jeniskelamin").text(
			$("input[name=gender]:checked").val()
		);
		$("#kabupaten").text(
			$("#fkabupaten").val()
		);
	});
	$("#reset").click(function(){
		$("#fnama").val("");
		$("#nama").text("");
		$("#falamat").val("");
		$("#alamat").text("");
		$("#jeniskelamin").text("");
		$("#kabupaten").text("");
	});
});